# Generated by Django 3.1.7 on 2021-03-28 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210328_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphone',
            old_name='sd_volune_max',
            new_name='sd_volume_max',
        ),
    ]
