# Generated by Django 3.1.7 on 2021-04-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_smartphone_sd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='products',
        ),
    ]
